{% set name = "ipyvue" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64ac7b789fb677182de5789c363b1d6c139e3f7c24ea20479c6cb699b73ac42c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyvue

about:
  home: http://github.com/mariobuikhuizen/ipyvue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Jupyter widgets base for Vue libraries'

  description: |
    Jupyter widgets base for Vue libraries

extra:
  recipe-maintainers:
    - mariobuikhuizen
