travis:
  secure:
    BINSTAR_TOKEN: NScJU8bczxPHF93R7HT+eJy98R33taOA1yfHC6IFg8Zp4nP+0O5cPN8rXfRISHQzN+QRZoQhUaqf4zkIq7nWvxBQqY5Ig5H9+OFPt/yk7GYdfEUhcylYHSU5xmbv6D/pfVEqVROvEWO5ebtoyr1wXEnQBy6o5UuHQHLSwMF6EohR/j9XL2g013G91C757y4OjgJJkOq2jW2bPyj+tPpkaOVO/lJcjfAWXEltgJ5qFTF4VlWcMLNtBZ+DxBiXIzmdHIb4hUik/xgEG/qtyIVxT2jH4KDIxkpMCAJNg1UtTmyBC3qbothSto/aAJKGAXITxwAL79z+cOJik2IFKBXzyncfzrgJG/ULpJmG5WDPESPTD84MGTBAbTsBDpd23Uy9BUmOJmpeXPlZaJoYzMZJEXLLT0ZeWqYZUYHg8n0lZXxZDiLHXMHuR5ZOqR6Hxhv3j1FNfoRaXcm5W/n52raFkZ9oaCTRjj7dPQ2aUNYistk9ouONCf7VkUINHS2SCyK/GKhsR5DQfZMfRfHeSQa5YMyBeyo4wbLVwdxWHhRTBFGNBKiFU7iUKYvGSgcS/YWv3xJcJ/uVEXAcEMuq7n4c5j627MuIr31HBaPldhQHaKwVkB/39V7ZkfAyz40GsnFX804Esw0a2MO4nAED/a3NdmM5Gu/gehSJnqrtfXRngtk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
